version: '3'

services:
  php:
    image: wodby/php:8.2
    container_name: php
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: www-data
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_EXTENSIONS_DISABLE: xhprof,spx
      PHP_XDEBUG_MODE: debug
      PHP_XDEBUG_CLIENT_HOST: host.docker.internal
      PHP_XDEBUG_START_WITH_REQUEST: 1
    volumes:
      - ./html:/var/www/html
      - ./docker-init/.env:/var/www/html/.env
      ## For Xdebug profiler traces (to view with Xhprof or Webgrind).
      # - files:/mnt/files

  apache:
    image: wodby/apache:2.4
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: info
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_SERVER_ROOT: /var/www/html
    volumes:
      - ./html:/var/www/html
    ports:
      - "${PORT}:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
  pma:
    image: phpmyadmin:latest  # https://hub.docker.com/_/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    ports:
      - "${IP}:8080:80"  # Ensure that ${IP} is set or replace with an actual IP
    links:
      - db:db

  db:
    image: mysql:8.0 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    # platform: linux/x86_64  # Uncomment if your machine is running on arm (ex: Apple Silicon processor)
    ports:
      - "${IP}:3306:3306"  # Ensure that ${IP} is set or replace with an actual IP
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d
      - wp_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  wp_data:
